### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Tall-KU-RideOn** [tcgoetz/GarminDB#114] opened 2021-03-03 13:34 UTC
**Describe the bug**
When running the binaries and trying to create files from connecting to Garmin Connect website, I get this error

```
Tylers-MBP:GarminDb_Darwin_2.0.0 tallku$ bash download_create_dbs.sh
Creating new DBs by downloading from Garmin Connect
___Downloading All Data___
Geting activities: '/Users/tallku/HealthData/FitFiles/Activities' (1000) temp /var/folders/33/f7r51_h14rx4rcy4k0k3qdc00000gn/T/tmpyo4trpn0
0activities [00:00, ?activities/s]
Traceback (most recent call last):
  File "garmin.py", line 341, in <module>
  File "garmin.py", line 322, in main
  File "garmin.py", line 127, in download_data
  File "download_garmin.py", line 283, in get_activities
  File "tqdm/std.py", line 1167, in __iter__
TypeError: 'NoneType' object is not iterable
[17406] Failed to execute script garmin
```

**Expected behavior**
downloaded files are processed

**Logs**
Please include a copy of screen logging and garmin.log.

**Please run bugreport.sh and attach bugreport.zip.**
[bugreport_1614778150.zip](https://github.com/tcgoetz/GarminDB/files/6076282/bugreport_1614778150.zip)

**Comment by Tall-KU-RideOn** [comment] 2021-03-03 13:44
This is happening on all Garmin Connect accounts.  I've tried 5, all have the same issue.  It is like Garmin changed the way activities are being downloaded....

**Comment by tcgoetz** [comment] 2021-03-03 14:19
The fix for this is on the develop branch and will be merged to master shortly.

**Comment by tcgoetz** [comment] 2021-03-03 14:19
dupe of #109

**Closed by tcgoetz** 2021-03-03 14:19 UTC
Labels: duplicate

**Comment by Tall-KU-RideOn** [comment] 2021-03-03 15:08
Thanks @tcgoetz - This was in the Binaries solution.  Will you be generating a new release?
