### ISSUE TITLE
Running make on windows 10 Makefile:216: recipe for target 'import_activities' failed

### ISSUE THREAD

**Issue by psychobas** [tcgoetz/GarminDB#21] opened 2019-01-07 19:10 UTC
Hi tcgoetz

First of all, thanks a lot for this code! I think it's a shame that Garmin doesn't allow to download csv files... 
I managed to get the scripts running on windows 10 by installing the Ubuntu subsystem just like you recommended. 

At first I got this error:
<img width="960" alt="2019-01-04 4" src="https://user-images.githubusercontent.com/44177662/50787441-b1550e00-12b6-11e9-88f8-01bd02a62f23.png">

I handled the error by rewriting the exception like this:
            except: 
                logger.error("Failed to parse %s:" % (file_name)) 

But now I run into a new error when the make file tried to build the database. I have data in the garmin, garmin_monitoring and even the activities database seems complete. But there is no data in the summary databases yet. Maybe this error stops the make file before these databases can be built? Do you have an idea how I could fix this error?
<img width="960" alt="2019-01-07" src="https://user-images.githubusercontent.com/44177662/50787776-aa7acb00-12b7-11e9-8fca-1219e85ce59f.png">

**Comment by tcgoetz** [comment] 2019-01-23 21:16
Sorry for the delay in getting back to you.

The summary stage runs last and will not run in a previous stage fails. I'll push a fix for the first error tonight. The second error may have nothing to do with the platform your running on. The screenshot only shows the bottom of the stack, but from that I can tell that the last file processed had a device entry with no manufacturer field. This is unexpected. Things like this have come up when people tried the script with new Garmin devices. What Garmin device do you have? Can you post the whole stack for the error? Can you post the  activity file it failed on to a file sharing site like Dropbox and send me the link?

**Comment by tcgoetz** [comment] 2019-01-27 22:59
I've fixed the issue with the TCX file you sent me. However the "Garmin Vivomove HR" is not in the product database. Can you send me a FIT file from that watch?

**Comment by psychobas** [comment] 2019-01-28 19:15
Thanks for the fix! I rerun the script and this time it failed here:
![image](https://user-images.githubusercontent.com/44177662/51859980-c57daf80-2338-11e9-9fd5-b43f8af2b50a.png)
The fit file that caused the fail is [here](https://www.dropbox.com/s/0i3v83qsyc3y20s/22124413342.fit?dl=0).

**Comment by tcgoetz** [comment] 2019-01-28 23:07
Try again. That file should work now: https://github.com/tcgoetz/Fit/commit/7c9939aa4d8e44cf3f54105991712318bea325d5

**Comment by psychobas** [comment] 2019-01-29 15:07
Thanks for the fix! I rerun the script but it failed at the same place with the same error message...

**Comment by tcgoetz** [comment] 2019-01-29 16:47
The fix was in the Fit submodule. Did you update the submodule?

When I download your fit file into ~/Downloads and run `make TEST_GC_ID=22124413342 test_monitoring_file` the whole file is parsed with no errors.

[22124413342.txt](https://github.com/tcgoetz/GarminDB/files/2808675/22124413342.txt)

**Comment by tcgoetz** [comment] 2019-01-29 16:53
If your debug output preceding the error includes
![screen shot 2019-01-29 at 11 52 36 am](https://user-images.githubusercontent.com/15090876/51925132-66fa1500-23bc-11e9-87f2-540d1830fe89.jpg)
then you don't have the fix.

**Comment by psychobas** [comment] 2019-01-30 08:15
You were right, sorry! I didn't have the fix. I now updated all the submodules:
![image](https://user-images.githubusercontent.com/44177662/51965018-88b0d600-2468-11e9-8b37-3a2ba78bd17c.png)
And rerun everything (first make setup and then build_dbs) but I got (almost) the same error message, but this time it recognized the watch:
<img width="960" alt="2019-01-30" src="https://user-images.githubusercontent.com/44177662/51965098-c4e43680-2468-11e9-9791-12c8d7d2fdb5.png">

I also run the make TEST you did and it run into the same error.

**Comment by tcgoetz** [comment] 2019-01-30 14:35
Please run `make TEST_GC_ID=22124413342 test_monitoring_file &> ~/Downloads/22124413342.txt` and share 22124413342.txt. I need more information since I can't duplicate the error.

**Comment by psychobas** [comment] 2019-01-30 16:00
I tried to run make `TEST_GC_ID=22124413342 test_monitoring_file --trace` which resulted this error:
![image](https://user-images.githubusercontent.com/44177662/51989584-ab161400-24a7-11e9-994d-5c8573e74ecd.png)

The fit file is in the same directory I run the command as well as in the Downloads folder on the Ubuntu Subsystem.

Running this command works:
`make TEST_GC_ID=22124413342 &> /mnt/c/Users/domin/GarminDB/22124413342.txt`
and results in [this ](https://www.dropbox.com/s/2jhmcusriptncvz/22124413342.txt?dl=0)textfile (I stopped the program after a couple of seconds since running it on the whole file takes about two hours). 
I will let it run now on the whole file and post it when finished (if this is the information you need?).

**Comment by tcgoetz** [comment] 2019-01-30 16:20
Try the updated code before doing anything else. (Run `make update`)

I was looking to get the debug output from running a test import of 22124413342.fit at higher debug level.

Running `make TEST_GC_ID=22124413342 test_monitoring_file` does a test import of that one file at higher debug level.

The test_monitoring_file make target can be seen here: https://github.com/tcgoetz/GarminDB/blob/9b5075cbd5ab0b8c7b45190218e57a31d6285f79/Makefile#L154

You error says that target doesn't exist which means your repo is out out date. Running `make update` updates all of your repos (the main GarminDB repo and the submodules).

**Comment by psychobas** [comment] 2019-01-30 16:45
Thanks for the fast reply! I updated the with `make update`:
![image](https://user-images.githubusercontent.com/44177662/51996936-0f3fd480-24b6-11e9-82cf-75e22067c823.png)
Running `make TEST_GC_ID=22124413342 test_monitoring_file` results in:
![image](https://user-images.githubusercontent.com/44177662/51997092-5cbc4180-24b6-11e9-945f-68fe90e1ce10.png)
Traceback reveals the same error as before:
![image](https://user-images.githubusercontent.com/44177662/51997150-7b223d00-24b6-11e9-9666-6b0fa62e6048.png)
Although the make target exists in my makefile... 
![image](https://user-images.githubusercontent.com/44177662/51997241-a4db6400-24b6-11e9-8658-889b1db18da4.png)

I feel like I might be doing something wrong, but I don't know what.

**Comment by tcgoetz** [comment] 2019-01-30 17:43
There's no text after "--sqlite" so it looks like $(TEST_DB_DIR) is not defined. It should get defined here: https://github.com/tcgoetz/GarminDB/blob/dbb3e60dd08e868a59fa4d532d406d46571a716a/Makefile#L49 .

I tracked this back to the Windows Ubuntu subsystem not defining TMPDIR. Update and try again.

**Comment by psychobas** [comment] 2019-01-30 18:08
Ok I updated and run the command again, getting this output:
![image](https://user-images.githubusercontent.com/44177662/52002360-17057600-24c2-11e9-8372-6800bb3bed00.png)
But as you can see the fit file is in the expected directory on the Ubuntu subsystem

**Comment by psychobas** [comment] 2019-01-30 18:41
Run from the directory where the makefile etc. is:
![image](https://user-images.githubusercontent.com/44177662/52003822-d9a2e780-24c5-11e9-9634-19fe5307ff31.png)
Run from the "home" directory:
![image](https://user-images.githubusercontent.com/44177662/52003878-048d3b80-24c6-11e9-8b5a-5539ffb370f5.png)
I'm not versatile in using the command line, but isn't it strange that "home" is not listed when using ls but I'm able to access it with cd /home?
![image](https://user-images.githubusercontent.com/44177662/52004075-9432ea00-24c6-11e9-9a77-e0d5d417353f.png)

**Comment by psychobas** [comment] 2019-01-30 18:46
I think I know what the problem is: I created the "Downloads" folder via the Windows Explorer, these folders seem not to get listed when using ls in Bash, as discussed [here](https://stackoverflow.com/questions/38600010/windows-10-and-wsl-directories-not-appearing-in-bash-when-created-in-file-expl).

**Comment by tcgoetz** [comment] 2019-01-30 21:47
BTW. I have made other changes. The original command may work now. If not we will have to work out getting debug output from your machine for the failing file.

**Comment by psychobas** [comment] 2019-02-01 18:13
I rerun the script again, unfortunately the same error (only the line numbers changed):
![image](https://user-images.githubusercontent.com/44177662/52140752-e48b8280-2653-11e9-8dce-b2f000d3c80c.png)

As already mentioned, understanding the scripts is beyond my programming skills. But the error log mentions that the error is due to timestamp_16 being of type none. I don't know what timestamp_16 is, but wouldn't it be possible to write an exception that catches the error and assigns timestamp_16 a value (e.g. 0) so that the + operator works? (I'm just trying to help, feeling bad for just reporting errors and not being able to help solve them) .

**Comment by tcgoetz** [comment] 2019-02-01 18:20
The problem is that timestamp_16 should be either not present or have a real value. The fact that is None means something went wrong earlier. 

I will push a change that papers over the error, but provides more info about the data message with a timestamp_16 field with value None.

The fact that the same file works for me on my platform, but failed for you on yours says that the message decoding is working differently between the two platforms.

**Comment by psychobas** [comment] 2019-02-02 08:40
It worked! Thank you so much you made my weekend :)
This time the output from the parsed file looked like this:
`INFO:/mnt/c/Users/domin/GarminDB/FitFileProcessor.pyc:file_id message: {'unknown_6': None, 'product': <GarminProduct.VivoMove_HR: 2772>, 'number': 19, 'time_created': datetime.datetime(2018, 6, 26, 17, 26, 59), 'serial_number': 3958547763, 'type': <FileType.monitoring_b: 32>, 'manufacturer': <Manufacturer.Garmin: 1>}
`
And the logger.error message states:
`ERROR:Fit.DataMessage:timestamp16 with value None: {'ascent': ascent(12.5787401575 ft (3834)), 'cum_ascent': cum_ascent(274.826115486 ft (83767)), 'timestamp_16': timestamp_16(None s (65535) [invalid])}`

**Comment by tcgoetz** [comment] 2019-02-02 20:30
If you have any further problems, please open an new issue. You may be interested in code committed today that automatically handles metric vs english units. You will need to rebuild your DB after updating to get the code (`make rebuild_dbs`).

**Closed by tcgoetz** 2019-02-02 20:30 UTC
