### ISSUE TITLE
Create_dbs error - Win10

### ISSUE THREAD

**Issue by schorbitz** [tcgoetz/GarminDB#32] opened 2019-09-01 10:55 UTC
Hi,
Getting this error trying to make create_dbs:

:~/GarminDB$ make create_dbs
python garmin.py --all --download --import --analyze
Geting activities: '/home/slacker/HealthData/FitFiles/Activities' (1000)
N/A% (0 of 1000) |                                                                                                                                                       | Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
  File "garmin.py", line 344, in <module>
    main(sys.argv[1:])
  File "garmin.py", line 334, in main
    download_data(overwite, latest, weight, monitoring, sleep, rhr, activities)
  File "garmin.py", line 97, in download_data
    download.get_activities(activities_dir, activity_count, overwite)
  File "/home/slacker/GarminDB/download_garmin.py", line 269, in get_activities
    activity_name_str = conversions.printable(activity['activityName'])
  File "/home/slacker/GarminDB/Fit/conversions.py", line 114, in printable
    return filter(lambda x: x in string.printable, string_in)
TypeError: 'NoneType' object is not iterable
Makefile:125: recipe for target 'garmin' failed
make: *** [garmin] Error 1

The first time I tried it successfully downloading ~1200 json files to /FitFiles/Activities but bailed around 20 minutes / 60% complete with the above message.
This is on a fresh install of the Windows Ubuntu Linux subsystem to which I've apt'd the following additional packages:
make python3 python3-pip ipython3 python-simplejson python-setuptools python-dateutil python-pip python-tk

Thanks

**Comment by tcgoetz** [comment] 2019-09-03 10:32
First, a couple of your packages are Python 3 packages. GarminDB is a Python 2 app still.

Second, it seems that you have an activity with no name, which is not something I expected. I am adding code to handle that.

**Comment by tcgoetz** [comment] 2019-09-11 02:01
Is this working for you now?

**Comment by tcgoetz** [comment] 2019-09-14 16:14
This is a duplicate of Issue #33.

**Comment by tcgoetz** [comment] 2019-09-14 16:14
Please confirm the fix in release 1.0.7.

**Closed** 2019-09-22 18:41 UTC
