### ISSUE TITLE
AssertionError in GarminDB During Login

### ISSUE THREAD

**Issue by juanvecino** [tcgoetz/GarminDB#253] opened 2024-12-07 13:19 UTC
**Description**

When running garmindb_cli.py to download data, the script fails with an AssertionError during the login process. This issue started unexpectedly after the script had been working for several weeks without problems.

**Steps to Reproduce**

Ensure GarminDB is installed (via Python files, as pip installation is currently difficult to use).
Run the garmindb_cli.py script with the --latest flag to download the latest data.
Observe the traceback error during execution.

**Expected Behavior**
The script should log in successfully and download the latest data.

**Actual Behavior**
An AssertionError occurs, specifically:

```
assert self.oauth1_token
AssertionError
Error Traceback

```
```

Traceback (most recent call last):
  File "/path/to/garmindb_cli.py", line 387, in <module>
    main(sys.argv[1:])
  File "/path/to/garmindb_cli.py", line 366, in main
    download_data(args.overwrite, args.latest, args.stats)
  File "/path/to/garmindb_cli.py", line 113, in download_data
    if not download.login():
           ^^^^^^^^^^^^^^^^
  File "/path/to/download.py", line 90, in login
    print(f"Username: {self.garth.username}")
                       ^^^^^^^^^^^^^^^^^^^
  File "/path/to/http.py", line 111, in username
    return self.profile["userName"]
           ^^^^^^^^^^^^
  File "/path/to/http.py", line 101, in profile
    self._profile = self.connectapi(
                    ^^^^^^^^^^^^^^^^
  File "/path/to/http.py", line 173, in connectapi
    resp = self.request(method, "connectapi", path, api=True, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/http.py", line 129, in request
    assert self.oauth1_token
           ^^^^^^^^^^^^^^^^^
AssertionError
```

**Additional Information**

Login Details: The username and password provided are correct and verified.
Installation Challenges: Installing GarminDB via pip has been difficult. The only reliable setup method has been cloning the repository and running the Python files directly.
Recent Change: The script successfully downloaded data until a few weeks ago. The issue started occurring without any apparent changes to the environment or credentials.

**Environment Details**

Python version: Python 3.12
GarminDB version: 3.6.1
OS: macOS

Does someone know how to solve it, or the reason for this problem?

**Comment by tcgoetz** [comment] 2024-12-07 14:01
Duplicate of #249 . Upgrade to 3.6.2

**Closed by tcgoetz** 2024-12-07 14:01 UTC
