### ISSUE TITLE
Try to update DB with latest fails

### ISSUE THREAD

**Issue by torp56** [tcgoetz/GarminDB#197] opened 2023-10-01 15:02 UTC
I submitted:
garmindb_cli.py --all --download --import --analyze --latest

**Logs**
C:\Users\Torp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts>garmindb_cli.py --all --download --import --analyze --latest
___Downloading Latest Data___
Traceback (most recent call last):
  File "C:\Users\Torp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\garmindb_cli.py", line 358, in <module>
    main(sys.argv[1:])
  File "C:\Users\Torp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\garmindb_cli.py", line 339, in main
    download_data(args.overwrite, args.latest, args.stats)
  File "C:\Users\Torp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\garmindb_cli.py", line 112, in download_data
    if not download.login():
  File "C:\Users\Torp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\garmindb\download.py", line 178, in login
    self.display_name = self.user_prefs['displayName']
TypeError: 'NoneType' object is not subscriptable

**Garmin.log:**
INFO:C:\Users\Torp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\garmindb\plugin_manager.py:Loading GarminDb plugins from C:\Users\Torp\HealthData\Plugins
INFO:C:\Users\Torp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\idbutils\plugin.py:Loading plugins from C:\Users\Torp\HealthData\Plugins
INFO:C:\Users\Torp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\idbutils\version.py:C:\Users\Torp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\garmindb_cli.py has been tested on Python 1...0...8
INFO:C:\Users\Torp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\idbutils\version.py:C:\Users\Torp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\garmindb_cli.py 1...0...8
INFO:root:Enabled statistics: [<Statistics.monitoring: 1>, <Statistics.steps: 2>, <Statistics.itime: 3>, <Statistics.sleep: 4>, <Statistics.rhr: 5>, <Statistics.weight: 6>, <Statistics.activities: 7>]
INFO:C:\Users\Torp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\garmindb_cli.py:___Downloading Latest Data___

**Please run bugreport.sh and attach bugreport.zip.**

Not sure howto do (?)

**Comment by tcgoetz** [comment] 2023-10-01 15:35
duplicate of #195 195

**Closed by tcgoetz** 2023-10-01 15:35 UTC
